logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
        - appid: wxcaf2078c0653b77d
          secret: 6f1794877ae846ca485b2a1bbb358ea9
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON
spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/miniprogram?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

file:
    uploadFolder : D://temp/


mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.github.binarywang.demo.wx.miniapp.*.pojo
